/**
 * Integração com o BiliTool (emr.bilitool.org) — executado NO SERVIDOR.
 * Busca a página de resultados (AAP 2022) e extrai as curvas de limiar, os
 * limiares pontuais e a recomendação, para desenhar o gráfico dentro do app.
 * A URL leva apenas números clínicos (idade/bilirrubina/IG/fatores) — sem
 * identificadores do paciente.
 */

export interface BiliPonto {
  x: number; // hora de vida
  y: number; // mg/dL
}

/** BT laboratorial extraída de "exames complementares" (por data). */
export interface BTExame {
  data: string; // ISO yyyy-mm-dd
  valor: number; // mg/dL
  hora?: string; // HH:mm, se constar no texto
}

/** Acha valores de BT (bilirrubina total) associados a datas no texto. */
export function parseBTExames(texto?: string | null): BTExame[] {
  if (!texto) return [];
  const dateRe = /(\d{1,2})\/(\d{1,2})\/(\d{2,4})/g;
  const idx: { iso: string; end: number; at: number }[] = [];
  let m: RegExpExecArray | null;
  while ((m = dateRe.exec(texto))) {
    const ano = m[3].length === 2 ? `20${m[3]}` : m[3];
    idx.push({ iso: `${ano}-${m[2].padStart(2, "0")}-${m[1].padStart(2, "0")}`, end: dateRe.lastIndex, at: m.index });
  }
  const out: BTExame[] = [];
  for (let i = 0; i < idx.length; i++) {
    const seg = texto.slice(idx[i].end, i + 1 < idx.length ? idx[i + 1].at : texto.length);
    // "BT 4,73" mas NÃO "BD"/"BI"; aceita "BT:" ou "BT ="
    const bt = seg.match(/\bBT\b\s*[:=]?\s*([\d]+(?:[.,]\d+)?)/i);
    if (!bt) continue;
    const hm = seg.match(/\b(\d{1,2})\s*[:h]\s*(\d{2})\b/);
    out.push({
      data: idx[i].iso,
      valor: Number(bt[1].replace(",", ".")),
      hora: hm ? `${hm[1].padStart(2, "0")}:${hm[2]}` : undefined,
    });
  }
  return out;
}
export interface BiliLimiar {
  resposta: string | null; // "Yes"/"No"
  mgdl: number | null;
}
export interface BilitoolResult {
  curvas: { fototerapia: BiliPonto[]; escalonamento: BiliPonto[]; exsanguineo: BiliPonto[] };
  paciente: BiliPonto[];
  limiares: {
    confirmarTSB: BiliLimiar;
    fototerapia: BiliLimiar;
    escalonamento: BiliLimiar;
    exsanguineo: BiliLimiar;
  };
  deltaTSB: { valor: number; direcao: "below" | "above"; idadeHoras: number } | null;
  seguimento: string | null;
  sourceUrl: string;
}

export interface BiliInput {
  pares: { idadeHoras: number; tsb: number }[];
  semanas: number; // 35–40
  fatoresRisco: boolean;
  unidade?: "US" | "SI"; // US = mg/dL
}

const BASE = "https://emr.bilitool.org/results.php";

export function buildBilitoolUrl(i: BiliInput): string {
  const pares = [...i.pares].sort((a, b) => a.idadeHoras - b.idadeHoras);
  const ageHours = pares.map((p) => p.idadeHoras).join(",");
  const totalBilirubin = pares.map((p) => p.tsb).join(",");
  const q = new URLSearchParams({
    ageHours,
    totalBilirubin,
    bilirubinUnits: i.unidade ?? "US",
    gestationalWeeks: String(Math.max(35, Math.min(40, Math.round(i.semanas)))),
    neuroRiskFactors: i.fatoresRisco ? "Yes" : "No",
  });
  return `${BASE}?${q.toString()}`;
}

const decode = (s: string) =>
  s
    .replace(/&nbsp;/g, " ")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&")
    .replace(/&#8805;/g, "≥")
    .replace(/&#8804;/g, "≤")
    .replace(/&Delta;/g, "Δ")
    .replace(/\s+/g, " ")
    .trim();

function pontosAposLabel(html: string, labelRe: RegExp): BiliPonto[] {
  const idx = html.search(labelRe);
  if (idx < 0) return [];
  const dm = html.slice(idx).match(/data:\s*\[([\s\S]*?)\]/);
  if (!dm) return [];
  const pts: BiliPonto[] = [];
  const re = /\{\s*x:\s*'?([\d.]+)'?\s*,\s*y:\s*'?([\d.]+)'?/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(dm[1]))) pts.push({ x: +m[1], y: +m[2] });
  return pts;
}

function limiar(texto: string, labelRe: RegExp): BiliLimiar {
  const m = texto.match(labelRe);
  return m ? { resposta: m[1] ?? null, mgdl: m[2] ? +m[2] : null } : { resposta: null, mgdl: null };
}

export function parseBilitool(html: string, sourceUrl: string): BilitoolResult {
  const texto = decode(html.replace(/<[^>]*>/g, " "));
  const delta = texto.match(
    /For the baby\s*([\d.]+)\s*mg\/dL\s*(below|above) the phototherapy threshold[\s\S]*?at\s*(\d+)\s*hours/i,
  );
  const segRaw = texto.match(/Postdischarge Follow Up\s*(.+?)(?:Generated by BiliTool|$)/i)?.[1];
  // remove a frase do Δ-TSB (já mostrada à parte); mantém a conduta de seguimento
  const seg = segRaw ? (segRaw.match(/If discharging[\s\S]*/i)?.[0] ?? segRaw) : null;

  return {
    curvas: {
      fototerapia: pontosAposLabel(html, /label:\s*"Phototherapy"/),
      escalonamento: pontosAposLabel(html, /label:\s*"Escalation of Care"/),
      exsanguineo: pontosAposLabel(html, /label:\s*"Exchange Transfusion"/),
    },
    paciente: pontosAposLabel(html, /label:\s*\[?\s*'Patient'/),
    limiares: {
      confirmarTSB: limiar(texto, /confirm with TSB\?\s*(Yes|No)\s*([\d.]+)\s*mg\/dL/i),
      fototerapia: limiar(texto, /Phototherapy\?\s*(Yes|No)\s*([\d.]+)\s*mg\/dL/i),
      escalonamento: limiar(texto, /Escalation of Care\?(?:\s*\(learn more\))?\s*(Yes|No)\s*([\d.]+)\s*mg\/dL/i),
      exsanguineo: limiar(texto, /Exchange Transfusion\?\s*(Yes|No)\s*([\d.]+)\s*mg\/dL/i),
    },
    deltaTSB: delta
      ? { valor: +delta[1], direcao: delta[2].toLowerCase() as "below" | "above", idadeHoras: +delta[3] }
      : null,
    seguimento: seg ? seg.slice(0, 400) : null,
    sourceUrl,
  };
}

export async function fetchBilitool(i: BiliInput): Promise<BilitoolResult> {
  const url = buildBilitoolUrl(i);
  const res = await fetch(url, {
    headers: {
      "User-Agent": "Mozilla/5.0 (compatible; EvolucaoAC/1.0)",
      Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "Accept-Language": "en-US,en;q=0.9",
    },
  });
  if (!res.ok) throw new Error(`BiliTool respondeu ${res.status}`);
  return parseBilitool(await res.text(), url);
}
